### ISSUE TITLE
Parsed exception stack item missing method name will be rejected by Application Insights

### ISSUE THREAD

**Issue by khaines** [khaines/angular-applicationinsights#12]
When parsing an unhandled exception stack, if a line is parsed without a method name, it is being sent to application insights as null/missing. This will be rejected by the endpoint, so in the cases of not being able to parse the method name, a filler/default name will need to be entered.

**Comment by arefkn** [comment]
First off, great work buddy! Within minutes I was able to pump values into appinsights.

I believe this open issue is for the screenshot below
![image](https://cloud.githubusercontent.com/assets/7892905/8104277/17c30130-104d-11e5-8c9c-a638e57aa2af.png)

Any ETA on this? This is very critical for my application and would be the deciding factor of whether I should use this library. (Sorry if that sounds offending - but I'm on a very tight schedule)

**Comment by arefkn** [comment]
Also, would this be the case for all unhandled exceptions?

**Comment by khaines** [comment]
Yes this issue is for the screenshot you sent. I've got a interim fix that will put some 'safe' default values in if it can't parse out the method name, so that AppInsights will at least accept the stack information.

**Comment by khaines** [comment]
I should have a patch out for this issue and the safari bug very shortly. I just want to get that safari bug fixed first .. this issue is already fixed in the master branch.

**Comment by khaines** [comment]
this should be resolved in the 0.2.4 package

**Comment by arefkn** [comment]
thank you! much appreciated
