### ISSUE TITLE
Remove one of the main file entries from the bower.json

### ISSUE THREAD

**Issue by alippai** [khaines/angular-applicationinsights#13]
Only one of the files is needed to run the application:
```
"main": ["dist/angular-applicationinsights.min.js", "dist/angular-applicationinsights.js"],
```
The docs say:
>string or array: The primary acting files necessary to use your package.

As angular apps are usually preprocessed, I recommend the non-minified version.

**Comment by khaines** [comment]
Thank you for your feedback

Both are provided so the consuming dev can choose which one to use. This is inline with what is done for npm and nuget distributions as well, and some app devs do use the pre-minified so it is preferred to leave that option open to them.
