### ISSUE TITLE
Infinite loop with Firefox + AdBlock

### ISSUE THREAD

**Issue by alippai** [khaines/angular-applicationinsights#14]
Firefox extensions throw synchronous error on xhr.open() instead of passing the error to the ```onerror``` callback handler. This causes angular-applicationinsights to get into an infinite loop as it catches the error and tries to send it - which results in an another error.

**Comment by khaines** [comment]
Thanks for reporting this. I'll investigate and try to reproduce the behaviour.

**Comment by khaines** [comment]
is there a particular adblock plug-in and version that causes this?

**Comment by alippai** [comment]
Disable a resource manually or add Google Analytics code and enable a
privacy list in adblock. If you need, I can create an example later today.

**Comment by khaines** [comment]
I managed to reproduce the behaviour you mentioned (endless looping of trying to report an error). I've got a fix drafted up and should be pushed shortly

**Comment by khaines** [comment]
This should be resolved now in v0.2.3
