### ISSUE TITLE
Crashes the web site in Safari 7/8

### ISSUE THREAD

**Issue by azzlack** [khaines/angular-applicationinsights#20]
Just ran into a problem with our Safari users where the page would not load when `angular-applicationinsights` was loaded. The page would load to ~25% and then stop responding, and had to be killed with the Activity Monitor.

I have no idea why it happens, but the problem was solved when I removed all `angular-applicationinsights` files and references in my js.

Please note that this problem did not exist in any other browser (IE11, FF, Chrome)

(I'm now tracking page views manually using the AI javascript sdk, but would really like this module to work)

**Comment by khaines** [comment]
Thank you for the feedback. I'll have a look into this....crashing Safari is not an intended behaviour.

**Comment by azzlack** [comment]
Thanks, the module works otherwise perfect, so would really love to be able to use it again.

Considering you are using a lot of 3rd part libraries/derivations for storage/stacktrace could it be one of them that has a problem with Safari?

**Comment by azzlack** [comment]
Btw. Here is the initialization code I was using: (Removed the unrelated parts)

```
angular.module('UltraReg', ["ngSanitize", "ui.router", 'ui.bootstrap', 'ui.bootstrap.tpls', 'ApplicationInsightsModule', 'ngAnimate', 'ngCookies', 'dndLists', 'uuid4', 'kendo.directives', 'ajoslin.promise-tracker', 'angular-data.DSCacheFactory', 'angulartics', 'angulartics.google.analytics2'])
    .config(['$httpProvider', '$analyticsProvider', 'applicationInsightsServiceProvider', function ($httpProvider, $analyticsProvider, applicationInsightsServiceProvider) {

        // Set up analytics and telementry
        applicationInsightsServiceProvider.configure('{my-id}', {});
    ]);
```

**Comment by khaines** [comment]
which version are you running by the way? I fixed something like this for Firefox...and I'm wondering if that did it for Safari too. The firefox issue would essentially get into an endless loop of trying to report an error and that would cause another error. 

I can't seem to get this to happen on my test pages in safari using 0.2.3
