### ISSUE TITLE
Add support for Browserify

### ISSUE THREAD

**Issue by sondreb** [khaines/angular-applicationinsights#28]
It's not possible to include the library using require('angular-applicationinsights'); in combination with Browserify and Gulp. 

Returns error: "Error: Cannot find module 'angular-applicationinsights'".

**Comment by sondreb** [comment]
All you need is a main entry point in the package.json, or perhaps use the browser field.

Like this: 
```json
"main": "build/angular-applicationinsights.min.js",
```

Have verified this loads the file correctly, but not verified if it actually works when embedded like this.

Could you also please include both minified and unminfied files with the npm package?

**Comment by sondreb** [comment]
Made a pull request for this change: https://github.com/khaines/angular-applicationinsights/pull/29

**Comment by khaines** [comment]
Thank you for that submission. It has been merged into the master branch.
